# Numpy Recap

## Arrays
We can initialize numpy arrays from nested Python lists and access elements using square brackets

In [1]:
import numpy as np

a = np.array([1, 2, 3]) # Create Rank 1 array
print("Type of a: ", type(a)) # Print type of a
print("Shape of a: ", a.shape) # Print dimensions of a
print("a[0]: {} a[1]: {} a[2]: {}".format(a[0], a[1], a[2])) # Prints the elements of a
a[0] = 5 # Change first element of a

b = np.array([[1, 2, 3], [4, 5, 6]]) # Create a rank 2 array
print("Shape of b: ", b.shape)
print("b[0, 0] = {} b[1, 1] = {} b[1, 2] = {}".format(b[0, 0], b[1, 1], b[1, 2])) # Same as b[i][j] for a 2d list.

Type of a:  <class 'numpy.ndarray'>
Shape of a:  (3,)
a[0]: 1 a[1]: 2 a[2]: 3
Shape of b:  (2, 3)
b[0, 0] = 1 b[1, 1] = 5 b[1, 2] = 6


Numpy also has many functions to create arrays.

In [13]:
a = np.zeros((2, 2)) # Create an array of zeros
print("Array of zeros:\n", a)

b = np.ones((1, 2)) # Create an array of all ones
print("\nArray of ones:\n", b)

c = np.full((2, 2), 7) # Create a constant array
print("\nConstant array of 7s:\n", c)

d = np.eye(2)  # Create a 2x2 identity matrix
print("\n2x2 Identity matrix:\n", d)

e = np.random.random((2, 2)) # Create an array filled with random values.
print("\nRandom 2x2 array:\n", e)

Array of zeros:
 [[0. 0.]
 [0. 0.]]

Array of ones:
 [[1. 1.]]

Constant array of 7s:
 [[7 7]
 [7 7]]

2x2 Identity matrix:
 [[1. 0.]
 [0. 1.]]

Random 2x2 array:
 [[0.19400201 0.88557686]
 [0.65087605 0.58858767]]


## Array Indexing

Numpy offers several ways to index into arrays e.g **slicing**, **integer array indexing**, **boolean array indexing**.

In [14]:
# Slicing examples

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Pull out the subarray consisting of the first 2 rows and columns 1 and 2;
b = a[:2, 1:3]
print("Array b:\n", b)

# Note: Modifying the slice of an array also modifies the original array.
b[0, 0] = 77
print("Array a after modifiying b:\n", a)

Array b:
 [[2 3]
 [6 7]]
Array a after modifiying b:
 [[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can mix integer indexing with slice indexing, however, this yields an array of lower rank than the original array.

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array
row_r1 = a[1, : ]
row_r2 = a[1:2, : ]
print("Rank 1 view of the second row of a:{} Shape:{}".format(row_r1, row_r1.shape))
print("Rank 2 view of the second row of a:{} Shape:{}".format(row_r2, row_r2.shape))

# Similarly for columns
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print("Rank 1 view of the second column of a:{} Shape:{}".format(col_r1, col_r1.shape))
print("Rank 2 view of the second column of a:{} Shape:{}".format(col_r2, col_r2.shape))

Rank 1 view of the second row of a:[5 6 7 8] Shape:(4,)
Rank 2 view of the second row of a:[[5 6 7 8]] Shape:(1, 4)
Rank 1 view of the second column of a:[ 2  6 10] Shape:(3,)
Rank 2 view of the second column of a:[[ 2]
 [ 6]
 [10]] Shape:(3, 1)


Integer array indexing allows to create arbitrary arrays using the data from another array (as opposed to slicing where the resulting array will always be a subarray of the original array)

In [20]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])

# The above is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# When using integer array indexing, you can reuse the same element from the source array.
# The following is equivalent to np.array([a[0, 1], a[0, 1]])
print(a[[0, 0], [1, 1]])

# Using integer array indexing to select or mutate one element from each row of a matrix:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Array b:\n", b)

# Create an array of indices
c = np.array([0, 2, 0, 1])

# Select one element from each row of b using the indices in c
print("Elements in each row of b from indices in c:\n", b[np.arange(4), c])

# Mutate one element from each row of b using the indices in c
b[np.arange(4), c] += 10
print("Array b after mutating:\n", b)

[1 4 5]
[1 4 5]
[2 2]
Array b:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Elements in each row of b from indices in c:
 [ 1  6  7 11]
Array b after mutating:
 [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing** lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [21]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2) # Find elements of a that are bigger than 2;
print(bool_idx)

# We can use boolean array indexing to construct a rank 1 array consisting of the elements 
# of a corresponding to the True values of bool_idx
print(a[bool_idx])

# All the above is equivalent to the following:
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Data types
Every numpy array is a grid of elements of the same type.

In [24]:
x = np.array([1, 2]) # Let numpy choose the datatype
print(x.dtype)

x = np.array([1., 2.])
print(x.dtype)

x = np.array([1., 2.], dtype=np.int64) # Force a particular data type
print(x)
print(x.dtype)

int64
float64
[1 2]
int64


## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module.

In [25]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum. (Can also use np.add(x, y))
print(x + y)

# Elementwise difference
print(y - x)

# Elementwise product
print(x * y)

# Elementwise division
print(x / y)

# Elementwise square root
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[4. 4.]
 [4. 4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


The `dot` function is used to compute inner products of vectors, to multiply a vector by a matrix and to multiply matrices. `dot` is available both as function in the numpy module and as an instance method of array objects.

In [28]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; can also use np.dot(v, w)
print("v . w = ", v.dot(w))

# Matrix / vector product;
print("x * v = ", x.dot(v))

# Matrix / matrix product; both produce the rank 2 array
print("x * y = \n", x.dot(y))

v . w =  219
x * v =  [29 67]
x * y = 
 [[19 22]
 [43 50]]


In [29]:
# Sum
x = np.array([[1, 2], [3, 4]])

print("Sum of elements in x: ", np.sum(x))
print("Sum of each column of x: ", np.sum(x, axis=0))
print("Sum of each row of x: ", np.sum(x, axis=1))

Sum of elements in x:  10
Sum of each column of x:  [4 6]
Sum of each row of x:  [3 7]


In [31]:
# Transpose
x = np.array([[1, 2], [3, 4]])
print("x:\n", x)

print("x transpose:\n", x.T)

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])
print("Rank 1 array v: ", v)
print("Transpose of v: ", v.T)

x:
 [[1 2]
 [3 4]]
x transpose:
 [[1 3]
 [2 4]]
Rank 1 array v:  [1 2 3]
Transpose of v:  [1 2 3]


## Broadcasting
Broadcasting allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [41]:
# Add a constant vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Using broadcasting to add v to each row of x

print("y:\n", y)

y:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:
1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

Functions that support broadcating are called [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

In [45]:
# Applications of broadcasting

# Compute the outer product of vectors
v = np.array([1, 2, 3]) # v has shape (3,)
w = np.array([4, 5]) # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w.
print("v (reshaped) * w =\n", np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x + v:\n", x + v)

# Add a vector to each column of a matrix
print("column add: x + w:\n", (x.T + w).T)
# Another way is to reshape w into a column vector and broadcast it directly against x
print("column add: x + w:\n", x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant. Numpy treats scalars as arrays of shape ()
print("x * 2=\n", x * 2)

v (reshaped) * w =
 [[ 4  5]
 [ 8 10]
 [12 15]]
x + v:
 [[2 4 6]
 [5 7 9]]
column add: x + w:
 [[ 5  6  7]
 [ 9 10 11]]
column add: x + w:
 [[ 5  6  7]
 [ 9 10 11]]
x * 2=
 [[ 2  4  6]
 [ 8 10 12]]


For more about numpy, checkout the [documentation](http://docs.scipy.org/doc/numpy/reference/).